name: rpccli
description: A command-line interface for my RPN calculator library.
version: 2.0.0

#dependencies:
#  path: ^1.4.1

environment:
    sdk: ">=2.0.0 <3.0.0"

dependencies:
  calculator:
    path: ../Calculator

dev_dependencies:
    test: "1.3.0"
