name: rpccli
description: A command-line interface for my RPN calculator library.
version: 1.0.0

#dependencies:
#  path: ^1.4.1

dependencies:
  calculator:
    path: /Users/paddy/Dropbox/src/dart/RPC/Calculator

dev_dependencies:
    test: "0.12.20+10"
